language: node_js
node_js:
  - "6.1.0"
  # - "5.0.0"
  # - "4.0.0"
script: npm run test:travis
before_script:
  # Generate a virtual framebuffer X server to collect Electron windows
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Wait for Xvfb to start
  - sleep 3
addons:
  apt:
    packages:
      - xvfb